package soalpsikotes;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Helsa
 */
public class Panel1 extends javax.swing.JPanel {
    /**
     * Creates new form Panel1
     */
    public Panel1() {
        
        initComponents();
        hapustbl();
        tampiltbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        void tampiltbl(){
        try{
            db_Koneksi konek = new db_Koneksi();
            Connection conn = konek.bukaKoneksi();
            Statement st = conn.createStatement();
            String sql = "select * from datauser order by Nama";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                String vNama = (rs.getString("Nama"));
                String vEmail = (rs.getString("Email"));

                String []data = {vNama,vEmail};
                DefaultTableModel tabmode = (DefaultTableModel) tabel.getModel();
                tabmode.addRow(data);
            }
            rs.close();
            conn.close();
        }catch(Exception e){
            System.out.print(e);
        }
    }
    
    void hapustbl(){        
        DefaultTableModel tabmode = (DefaultTableModel) tabel.getModel();
        int brs = tabmode.getRowCount();
        for (int i = 0; i < brs; i++) {
            tabmode.removeRow(0);
	}
    }
    
    void CariTable(){
        hapustbl();
        try{
            db_Koneksi konek = new db_Koneksi();
            Connection conn = konek.bukaKoneksi();
            Statement st = conn.createStatement();
            String sql = "select * from datauser where Nama like '%"+ TxtTable.getText() +"%' ";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                String vNama = (rs.getString("Nama"));
                String vEmail = (rs.getString("Email"));

                String []data = {vNama,vEmail};
                DefaultTableModel tabmode = (DefaultTableModel) tabel.getModel();
                tabmode.addRow(data);
            }
            rs.close();
            conn.close();
        }catch(Exception e){
            System.out.print(e);
        } 
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtTable = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(TxtTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 91, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama", "Email"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 380, 140));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel5.setText("Nama :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CariTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

}
